"""
TNP AI Helpdesk — Main Streamlit App (Person 3's file)

This is the Home page / entry point for the whole app. Run it with:
    streamlit run streamlit_app.py

It does 3 things (your assigned scope):
  1. Chat interface  -> talks to the LangGraph pipeline (router + nodes)
                         built by teammates (Person 1 + Person 2).
  2. Eligibility checker sidebar -> instant, non-LLM lookup using
                         eligibility_criteria.json (fast + always accurate,
                         no waiting on the model / no hallucination risk).
  3. Page layout      -> pages/2_Policies.py sits in the pages/ folder next
                         to this file, so Streamlit auto-builds the sidebar
                         nav ("streamlit_app" + "Policies") with no extra code.

--------------------------------------------------------------------------
CONFIRMED FOLDER STRUCTURE (from `git ls-files`)
--------------------------------------------------------------------------
tnp-ai-helpdesk/
├── streamlit_app.py                <- this file (repo root — was "app.py",
│                                        renamed to avoid colliding with the
│                                        app/ package folder below)
├── pages/
│   └── 2_Policies.py                <- moved here from data/
├── main.py                         <- has build_graph()
├── app/
│   ├── state.py
│   ├── agent/
│   │   ├── router.py
│   │   ├── lllmclient.py
│   │   └── llm_embedding.py
│   ├── nodes/
│   │   ├── eligibility.py          <- RAG-based node, used by the chat pipeline
│   │   ├── general.py
│   │   ├── guidelines.py
│   │   └── placements.py
│   └── rag/
│       └── retriever_singleton.py
├── utils/
│   ├── rag_chain.py
│   └── eligibility.py              <- plain JSON lookup, THIS file imports it
├── data/
│   ├── documents/                  <- PDFs for the RAG index
│   ├── TNP_Placement_Data.xlsx
│   └── eligibility_criteria.json
└── faiss_index/tnp_index/          <- generated by build_index.py

Note: app/nodes/eligibility.py and utils/eligibility.py are two DIFFERENT
files that happen to share a filename in different folders — that's fine,
just don't get them mixed up when editing.
"""

import streamlit as st

st.set_page_config(page_title="TNP AI Helpdesk", page_icon="🎓", layout="wide")

# ---------------------------------------------------------------------
# Imports from teammates' code — wrapped so a bad path gives a friendly
# error instead of a raw traceback.
# ---------------------------------------------------------------------
try:
    from main import build_graph
except Exception as e:
    st.error(
        "Couldn't import `build_graph` from main.py. Make sure streamlit_app.py "
        f"sits in the same folder as main.py (repo root).\n\nDetails: {e}"
    )
    st.stop()

try:
    from utils.eligibility import load_companies, get_company_names, check_eligibility
except Exception as e:
    st.error(
        "Couldn't import the eligibility checker. Make sure the file with "
        "load_companies() / get_company_names() / check_eligibility() is "
        f"saved at utils/eligibility.py.\n\nDetails: {e}"
    )
    st.stop()


# ---------------------------------------------------------------------
# Cache the compiled LangGraph app so it's only built once per session,
# not re-built on every single chat message / rerun.
# ---------------------------------------------------------------------
@st.cache_resource
def get_app():
    return build_graph()


graph_app = get_app()

# ---------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []  # [{"role": "user"/"assistant", "content": str}]

if "student" not in st.session_state:
    st.session_state.student = {"name": "", "branch": "", "year": "1"}


# ================= SIDEBAR =================
with st.sidebar:
    st.header("👋 Your Details")
    st.session_state.student["name"] = st.text_input(
        "Name", st.session_state.student["name"], placeholder="e.g. Aanya"
    )
    st.session_state.student["branch"] = st.text_input(
        "Branch", st.session_state.student["branch"], placeholder="e.g. IT"
    )
    st.session_state.student["year"] = st.selectbox(
        "Year", ["1", "2", "3", "4"],
        index=["1", "2", "3", "4"].index(st.session_state.student["year"]),
    )

    st.divider()

    st.header("✅ Quick Eligibility Checker")
    st.caption("Instant check against our records — no need to chat for this.")

    companies = get_company_names()
    all_branches = sorted(
        {b for c in load_companies() for b in c["eligible_branches"] if b != "All Branches"}
    )

    with st.form("eligibility_form"):
        sel_company = st.selectbox("Company", companies)
        sel_cgpa = st.number_input("Your CGPA", min_value=0.0, max_value=10.0, step=0.1, value=7.5)
        sel_backlogs = st.number_input("Active backlogs", min_value=0, max_value=10, step=1, value=0)
        sel_branch = st.selectbox("Your branch", all_branches)
        submitted = st.form_submit_button("Check Eligibility")

    if submitted:
        eligible, reasons = check_eligibility(sel_company, sel_cgpa, sel_backlogs, sel_branch)
        if eligible:
            st.success(f"✅ You're ELIGIBLE for {sel_company}")
        else:
            st.error(f"❌ Not eligible for {sel_company} right now")
        for r in reasons:
            st.write(f"- {r}")

    st.divider()

    st.header("💬 Ask about")
    query_type_label = st.radio(
        "Pick a category, then type your question below",
        ["Placement Stats", "Guidelines", "Eligibility", "General"],
        index=3,
    )
    query_type_map = {
        "Placement Stats": "placement",
        "Guidelines": "guideline",
        "Eligibility": "eligibility",
        "General": "general",
    }

    if st.button("🗑️ Clear chat"):
        st.session_state.messages = []
        st.rerun()


# ================= MAIN CHAT AREA =================
st.title("🎓 TNP AI Helpdesk")

name = st.session_state.student["name"]
st.caption(
    f"Hi {name}! Ask me about placement stats, interview/OA guidelines, or eligibility."
    if name else
    "Ask me about placement stats, interview/OA guidelines, or eligibility."
)

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

user_query = st.chat_input("Type your question...")

if user_query:
    st.session_state.messages.append({"role": "user", "content": user_query})
    with st.chat_message("user"):
        st.markdown(user_query)

    # Prepend the chosen category keyword, same trick main.py's CLI uses,
    # so router_node's keyword matching reliably picks the right node.
    full_query = f"{query_type_map[query_type_label]} {user_query}"

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                result = graph_app.invoke({"user_query": full_query})
                response = result.get("response", "Sorry, I couldn't generate a response.")
            except Exception as e:
                response = f"Something went wrong while generating a response: {e}"
        st.markdown(response)

    st.session_state.messages.append({"role": "assistant", "content": response})
